
-- DROP e CREATE UTENTE_PAY
DROP TABLE IF EXISTS CONTO_CORRENTE CASCADE;
DROP TABLE IF EXISTS UTENTE_PAY CASCADE;

CREATE TABLE UTENTE_PAY (
  ID_UTENTE_PAY SERIAL PRIMARY KEY,
  EMAIL TEXT UNIQUE NOT NULL,
  NOME TEXT,
  COGNOME TEXT,
  DATA_REG TIMESTAMP DEFAULT NOW()
);

CREATE TABLE CONTO_CORRENTE (
  ID_CONTO SERIAL PRIMARY KEY,
  ID_UTENTE_PAY INT REFERENCES UTENTE_PAY(ID_UTENTE_PAY) ON DELETE CASCADE,
  SALDO NUMERIC(10,2) DEFAULT 100.00
);

-- INSERT utenti di esempio
INSERT INTO UTENTE_PAY (EMAIL, NOME, COGNOME) VALUES
  ('alice@example.com', 'Alice', 'Rossi'),
  ('bob@example.com', 'Bob', 'Bianchi'),
  ('carlo@example.com', 'Carlo', 'Verdi');

-- Crea i conti per ciascun utente
INSERT INTO CONTO_CORRENTE (ID_UTENTE_PAY, SALDO)
SELECT ID_UTENTE_PAY, 100.00 FROM UTENTE_PAY;
